---

- name: Docker systemd service directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Proxy File
  template:
    src: docker_proxy.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    owner: root
    group: root
    mode: 0644
  register: docker_proxy_file

- name: Trigger systemctl update
  set_fact:
    docker_daemon_reload: true
    docker_service_state: restarted
  when: docker_proxy_file.changed

...