---

- name: Distribution Check
  when: ansible_distribution != "Ubuntu"
  fail:
    msg: "Docker configuration only supported on Ubuntu hosts."

# Consistent state before we start
- name: Flush Handlers
  meta: flush_handlers

- name: Sysctl settings
  sysctl:
    name: vm.max_map_count
    value: "{{ docker_vm_max_map_count }}"
    reload: true
  when: "docker_vm_max_map_count != ''"

# Firewall configuration
- name: Firewall configuration
  include_tasks: firewall.yml

# Package configuration
- name: Package configuration
  include_tasks: packages.yml

# Docker configuration
- name: Docker Configuration
  include_tasks: config.yml

# Configure docker services
- name: Flush Handlers
  meta: flush_handlers

- name: Enable containerd service
  service:
    name: containerd
    state: started
    enabled: true

- name: Enable Docker service
  service:
    name: docker
    state: started
    enabled: true

# Docker user configuration
- name: Allow users to access docker
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"

# Swarm configuration
- name: Configure swarm
  when: docker_swarm_configure | default(false)
  include_tasks: swarm.yml

- name: Prune schedule
  ansible.builtin.include_tasks: prune.yml
