---

- name: Distribution Check
  when: ansible_distribution != "Ubuntu"
  fail:
    msg: "Docker configuration only supported on Ubuntu hosts."

- name: Set defaults
  set_fact:
    docker_service_state: "started"
    docker_daemon_reload: false

- name: Sysctl settings
  sysctl:
    name: vm.max_map_count
    value: 262144
    reload: true

# Firewall configuration
- name: Firewall configuration
  include_tasks: firewall.yml

# Package configuration
- name: Package configuration
  include_tasks: packages.yml

# Daemon configuration
- name: Configure Docker daemon
  template:
    dest: /etc/docker/daemon.json
    src: daemon.json.j2
    owner: root
    group: root
    mode: 0644
  register: daemon_config

- name: Trigger docker daemon restart
  set_fact:
    docker_service_state: "restarted"
  when: daemon_config.changed

# Docker proxy configuration
- name: Docker proxy
  include_tasks: docker_proxy.yml

# Configure docker services
- name: Reload services
  command: "systemctl daemon-reload"
  when: "docker_daemon_reload|default(false)"

- name: Enable Docker service
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: true

# Docker user configuration
- name: Allow users to access docker
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"
  when: docker_users is defined

# Swarm configuration
- name: Configure swarm
  when: docker_swarm_configure | default(false)
  include_tasks: swarm.yml

...