---

# Repo configuration
- name: Old apt repository remove
  apt_repository:
    repo: >-
      deb https://download.docker.com/linux/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} stable
    state: absent

- name: Add docker repositories/builds
  ansible.builtin.deb822_repository:
    name: docker
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    suites: "{{ ansible_distribution_release }}"
    state: present
    enabled: true
    components: [stable]
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"

- name: Force update of Apt cache
  ansible.builtin.apt:
    update_cache: true
  ignore_errors: true
  changed_when: false

# Remove packages
- name: Remove packages
  package:
    name:
      - docker.io
      - docker-cli
    state: absent

# Add packages
- name: Add packages
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-docker
    state: present

