---

# Repo configuration
- name: Add docker repository key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add docker repositories/builds
  apt_repository:
    repo: >-
      deb https://download.docker.com/linux/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes

- name: Force update of Apt cache
  apt:
    update_cache: true
  ignore_errors: true
  changed_when: false

# Remove packages
- name: Remove packages
  package:
    name:
      - docker.io
    state: absent

# Add packages
- name: Add packages
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-docker
      - docker-compose
    state: present
